/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package daw;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author clara
 */
public class PanelPrincipal extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form PanelPrincipal
     */
    // Atributos de la clase (privados)
    private PanelBotones botonera;
    private JTextArea areaTexto;
    private int tipoOperacion;

    // Constructor
    public PanelPrincipal() {
        initComponents();
        inicializacionComponentes();
        tipoOperacion = -1; // No hay operaciones en la calculadora
    }

    // Se inicializan los componentes gráficos y se colocan en el panel
    private void inicializacionComponentes() {
        // Creamos el panel de botones
        botonera = new PanelBotones();
        // Creamos el área de texto
        areaTexto = new JTextArea(10, 20);
        areaTexto.setEditable(false);
        areaTexto.setBackground(Color.white);

        //Establecemos layout del panel principal
        this.setLayout(new BorderLayout());
        // Colocamos la botonera y el área texto
        this.add(areaTexto, BorderLayout.NORTH);
        this.add(botonera, BorderLayout.SOUTH);
        for (JButton boton : this.botonera.getgrupoBotones()) {
            boton.addActionListener(this);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        // Se obtiene el objeto que desencadena el evento
        Object o = e.getSource();

        // Si es el botón para borrar se borra 
        if (o.equals(this.botonera.grupoBotones[15])) {
            areaTexto.setText("");
            // RESTO DEL CÓDIGO DE LA LÓGICA DE LA CALCULADORA

            //si es un botón   
        } else if (o instanceof JButton) {
            String texto = ((JButton) o).getText();
            switch (texto) {
                case "+":
                    tipoOperacion = 1;
                    areaTexto.setText(areaTexto.getText() + "+");
                    break;
                case "-":
                    tipoOperacion = 2;
                    areaTexto.setText(areaTexto.getText() + "-");
                    break;
                case "*":
                    tipoOperacion = 3;
                    areaTexto.setText(areaTexto.getText() + "*");
                    break;
                case "/":
                    tipoOperacion = 4;
                    areaTexto.setText(areaTexto.getText() + "/");
                    break;
                case "=":
                    String[] numeros = areaTexto.getText().split("\\+|\\-|\\*|\\/");
                    try {

                        calcularResultado(tipoOperacion, Double.parseDouble(numeros[0]), Double.parseDouble(numeros[1]));

                    } catch (Exception ex) {
                        areaTexto.setText("Error de cálculo");
                        //areaTexto.setText("");
                        tipoOperacion = -1;
                    }
                    break;
                case "C":
                    areaTexto.setText("");
                    tipoOperacion = -1;
                    break;
                default:
                    areaTexto.setText(areaTexto.getText() + texto);
                    break;
            }
        }

    }

    //método para realizar los cálculos
    private double calcularResultado(int tipoOperacion, double num1, double num2) {
        double resultado = 0;
        switch (tipoOperacion) {
            case 1: //suma
                resultado = num1 + num2;
                areaTexto.setText(Integer.toString((int) resultado));
                break;
            case 2: //resta
                resultado = num1 - num2;
                areaTexto.setText(Integer.toString((int) resultado));
                break;
            case 3: //multiplicación
                resultado = num1 * num2;
                areaTexto.setText(Integer.toString((int) resultado));
                break;
            case 4: //división
                if (num2 == 0) {
                    resultado = num1 / num2;
                    areaTexto.setText(Double.toString(resultado));
                    areaTexto.setText("No se puede dividir entre cero");
                    //areaTexto.setText("");
                    tipoOperacion = -1;
                    return 0;
                }
                resultado = num1 / num2;
                areaTexto.setText(Double.toString(resultado));
                break;
        }
        return resultado;
    }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

